image: docker:20.10.16
variables:
  GIT_DEPTH: '0' 

#include:
#  - local: 'ci-templates/install.yml'

stages:
  - build
  - test
  - release
  - deploy

workflow:
    rules:
      - if: $CI_COMMIT_REF_NAME ==  $CI_DEFAULT_BRANCH
        variables:
          DOCKER_TLS_CERTDIR: ""
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/mosu-utdb-api
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:latest
          CONTAINER_NAME: mosu-utdb-api
          CD_URL: http://portainer.ethicsinfotech.in:9443/api/stacks/webhooks/0dd69a22-153e-4699-850a-4a1ceddffacb

build:
  stage: build
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .

release:
  stage: release
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY 
  script:
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

deploy:
  stage: deploy
  script:
    - apk add --update curl
    - curl -XPOST $CD_URL